name: Lockout
version: '${project.version}'
main: com.mcplugin.cdelc.lockout.Lockout
api-version: 1.18
authors: [ Carden ]
description: Adds minecraft lockout games to your server
commands:
  lockoutaddall:
    description: Add all online players to the lockout game
    usage: /lockoutaddall
  lockoutadd:
    description: Add the specified player to the lockout game
    usage: /lockoutadd [player]
  lockoutremove:
    description: Remove the specified player from the lockout game
    usage: /lockoutremove [player]
  lockoutabsolutedifficulty:
    description: Sets the minimum and maximum task difficulties of the lockout game
    usage: /lockoutabsolutedifficulty [difficulty]
  lockoutmaxdifficulty:
    description: Sets the maximum task difficulty of the lockout game
    usage: /lockoutmaxdifficulty [difficulty]
  lockoutmindifficulty:
    description: Sets the minimum task difficulty of the lockout game
    usage: /lockoutmindifficulty [difficulty]
  lockoutnumtasks:
    description: Sets the number of tasks to be generated in this game
    usage: /lockoutnumtasks [tasks]
  lockoutreset:
    description: Stops any running game and resets all settings to their defaults
    usage: /lockoutreset
  lockoutsettings:
    description: View the current settings of the lockout game
    usage: /lockoutsettings
  lockoutstart:
    description: Start the lockout game
    usage: /lockoutstart
  lockoutstop:
    description: Stop the lockout game
    usage: /lockoutstop